ITBedrijf/ITBedrijf/Controllers/KassaController.cs
using ITBedrijf.DataAccess;
using ITBedrijf.Extra;
using ITBedrijf.Hubs;
using ITBedrijf.Models;
using ITBedrijf.PresentationModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ITBedrijf.Controllers
{
    public class KassaController : Controller
    {
        // GET: Kassa
        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult Index(int? offset, int? aantal)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (!offset.HasValue) offset = 0;
            if (!aantal.HasValue) aantal = 10;
            List<Register> register = DARegister.GetRegisters(offset.Value, aantal.Value);
            List<int> numbers = LimitList.GetNumberList(LimitList.GetAantal(DARegister.GetRegistersCount(), aantal.Value));
            ViewBag.Register = register;
            ViewBag.Numbers = numbers;
            ViewBag.Length = numbers.Count();
            return View();
        }
        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult NewRegister()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            return View();
        }

        [HttpPost]
        public ActionResult NewRegister(PMRegister register, DateTime? purchaseTime, DateTime? expireTime)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (ModelState.IsValid)
            {
                if (register.PurchaseDate >= register.ExpireDate) return View(register);
                if (purchaseTime.HasValue) register.PurchaseDate = new DateTime(register.PurchaseDate.Year, register.PurchaseDate.Month, register.PurchaseDate.Day, purchaseTime.Value.Hour, purchaseTime.Value.Minute, 0);
                if (expireTime.HasValue) register.ExpireDate = new DateTime(register.ExpireDate.Year, register.ExpireDate.Month, register.ExpireDate.Day, expireTime.Value.Hour, expireTime.Value.Minute, 0);
                DARegister.InsertRegister(register);
                var hub = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<Counters>();
                int amountRegisters = DARegister.GetRegistersCount();
                hub.Clients.All.NumberOffRegisters(amountRegisters);
                return RedirectToAction("Index");
            }
            return View(register);
        }

        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult Log(int id, int? offset, int? aantal)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (!offset.HasValue) offset = 0;
            if (!aantal.HasValue) aantal = 10;
            List<Errorlog> log = DALog.GetLogsById(id, offset.Value, aantal.Value);
            List<int> numbers = LimitList.GetNumberList(LimitList.GetAantal(DALog.GetErrorlogsCount(id), aantal.Value));
            ViewBag.Log = log;
            ViewBag.Numbers = numbers;
            ViewBag.Length = numbers.Count();
            ViewBag.Id = id;
            return View();
        }

        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult Logs(int? offset, int? aantal)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (!offset.HasValue) offset = 0;
            if (!aantal.HasValue) aantal = 10;
            List<Errorlog> log = DALog.GetErrorlog(offset.Value, aantal.Value);
            List<int> numbers = LimitList.GetNumberList(LimitList.GetAantal(DALog.GetErrorlogsCount(), aantal.Value));
            ViewBag.Log = log;
            ViewBag.Length = numbers.Count();
            ViewBag.Numbers = numbers;
            return View();
        }
    }
}

ITBedrijf/ITBedrijf/Views/Kassa/Index.cshtml
@model PMRegister
<script src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
<script src="~/signalr/hubs"></script>
<h2>Kassa Overzicht</h2>
<p id="amountRegisters"></p>
<table>
    <tr class="header">
        <td>@Html.LabelFor(a => a.RegisterName)</td>
        <td>@Html.LabelFor(a => a.Device)</td>
        <td>@Html.LabelFor(a => a.PurchaseDate)</td>
        <td>@Html.LabelFor(a => a.ExpireDate)</td>
        <td></td>
    </tr>
    @foreach (var item in @ViewBag.Register)
    {
        <tr class="item">
            <td>@item.RegisterName</td>
            <td>@item.Device</td>
            <td>@item.PurchaseDate</td>
            <td>@item.ExpireDate</td>
            <td><a href="/Kassa/Log?id=@item.Id">Logs</a></td>
        </tr>
    }
    <tr class="link">
        <td><a href="/Kassa/NewRegister">Kassa Toevoegen</a></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
<p>
    @foreach (var item in @ViewBag.Numbers)
    {
        if (@item != @ViewBag.Length - 1)
        {
            <a href="/Kassa/Index?Offset=@item">@item</a>
            <span> - </span>
        }
        else
        {
            <a href="/Kassa/Index?Offset=@item">@item</a>
        }
    }
</p>
<script>
    $(function () {
        var counters = $.connection.counters;
        $.connection.hub.start().done(function () {
            counters.server.getAmountRegisters();
        });

        counters.client.numberOffRegisters = function (numberOffFiles) {
            $('#amountRegisters').text("Totaal aantal kassa's: " + numberOffFiles);
        }
    });
</script>

ITBedrijf/ITBedrijf/Views/Kassa/Log.cshtml
@model PMLog
<h2>Logs Overzicht</h2>
<table>
    <tr class="header">
        <td class="longer">@Html.LabelFor(a => a.RegisterName):@Html.LabelFor(a => a.Device)</td>
        <td>@Html.LabelFor(a => a.Timestamp)</td>
        <td>@Html.LabelFor(a => a.Message)</td>
        <td>@Html.LabelFor(a => a.Stacktrace)</td>
    </tr>
    @foreach (var item in @ViewBag.Log)
    {
        <tr class="item">
            <td class="longer">@item.RegisterName:@item.Device</td>
            <td>@item.Timestamp</td>
            <td>@item.Message</td>
            <td>@item.Stacktrace</td>
        </tr>
    }
    <tr class="link">
        <td class="longer"><a href="/Kassa/Index">Keer Terug</a></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
<p>
    @foreach (var item in @ViewBag.Numbers)
    {
        if (@item != @ViewBag.Length - 1)
        {
            <a href="/Kassa/Log?id=@ViewBag.Id&Offset=@item">@item</a>
            <span> - </span>
        }
        else
        {
            <a href="/Kassa/Log?id=@ViewBag.Id&Offset=@item">@item</a>
        }
    }
</p>

ITBedrijf/ITBedrijf/Views/Kassa/Logs.cshtml
@model PMLog
<script src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
<script src="~/signalr/hubs"></script>
<h2>Logs Overzicht</h2>
<p id="amountLogs"></p>
<table>
    <tr class="header">
        <td class="longer">@Html.LabelFor(a => a.RegisterName):@Html.LabelFor(a => a.Device)</td>
        <td>@Html.LabelFor(a => a.Timestamp)</td>
        <td>@Html.LabelFor(a => a.Message)</td>
        <td>@Html.LabelFor(a => a.Stacktrace)</td>
    </tr>
    @foreach (var item in @ViewBag.Log)
    {
        <tr class="item">
            <td class="longer">@item.RegisterName:@item.Device</td>
            <td>@item.Timestamp</td>
            <td>@item.Message</td>
            <td>@item.Stacktrace</td>
        </tr>
    }
</table>
<p>
    @foreach (var item in @ViewBag.Numbers)
    {
        if (@item != @ViewBag.Length-1)
        {
            <a href="/Kassa/Logs?Offset=@item">@item</a>
        <span> - </span>
        }
        else
        {
            <a href="/Kassa/Logs?Offset=@item">@item</a>
        }
    }
</p>
<script>
    $(function () {
        var counters = $.connection.counters;
        $.connection.hub.start().done(function () {
            counters.server.getAmountLogs();
        });

        counters.client.numberOffLogs = function (numberOffFiles) {
            $('#amountLogs').text("Totaal aantal Logs: " + numberOffFiles);
        }
    });
</script>

ITBedrijf/ITBedrijf/Views/Kassa/NewRegister.cshtml
@model PMRegister
<h2>Kassa Toevoegen</h2>

@using (Html.BeginForm("NewRegister", "Kassa", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table class="form">
        <tr>
            <td>@Html.LabelFor(a => a.RegisterName)</td>
            <td>@Html.TextBoxFor(a => a.RegisterName, new { placeholder = Html.DisplayNameFor(a => a.RegisterName) })</td>
            @Html.ValidationMessageFor(a => a.RegisterName)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Device)</td>
            <td>@Html.TextBoxFor(a => a.Device, new { placeholder = Html.DisplayNameFor(a => a.Device) })</td>
            @Html.ValidationMessageFor(a => a.Device)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.PurchaseDate)</td>
            <td><input type="date" value="@DateTime.Today" id="PurchaseDate" name="PurchaseDate" min="@DateTime.Today.Year-@DateTime.Today.Month-@DateTime.Today.Day" /></td>
            <td><input type="time" value="@DateTime.Today" id="PurchaseTime" name="PurchaseTime" /></td>
            @Html.ValidationMessageFor(a => a.PurchaseDate)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.ExpireDate)</td>
            <td><input type="date" value="@DateTime.Today" id="ExpireDate" name="ExpireDate" min="@DateTime.Today.AddDays(1).Year-@DateTime.Today.AddDays(1).Month-@DateTime.Today.AddDays(1).Day" /></td>
            <td><input type="time" value="@DateTime.Today" id="ExpireTime" name="ExpireTime" /></td>
            @Html.ValidationMessageFor(a => a.ExpireDate)
        </tr>
        <tr>
            <td><input type="submit" value="Kassa Toevoegen" /></td>
            <td>
                <a href="/Kassa/Index">
                    <input type="button" value="Keer Terug" />
                </a>
            </td>
            <td></td>
        </tr>
    </table>
}