ITBedrijf/ITBedrijf/Models/Register.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ITBedrijf.Models
{
    public class Register
    {
        public int Id { get; set; }
        public int Index { get; set; }

        [Required]
        [DisplayName("Naam Kassa")]
        [StringLength(100, ErrorMessage = "Het {0} moet minstens {2} karakters lang zijn.", MinimumLength = 2)]
        public string RegisterName { get; set; }

        [Required]
        [DisplayName("Naam Toestel")]
        [StringLength(100, ErrorMessage = "Het {0} moet minstens {2} karakters lang zijn.", MinimumLength = 2)]
        public string Device { get; set; }

        [Required]
        [DisplayName("Aankoop Datum")]
        public DateTime PurchaseDate { get; set; }

        [Required]
        [DisplayName("Verval Datum")]
        public DateTime ExpireDate { get; set; }
    }
}

ITBedrijf/ITBedrijf/Controllers/VerenigingController.cs
using ITBedrijf.DataAccess;
using ITBedrijf.Extra;
using ITBedrijf.Hubs;
using ITBedrijf.Models;
using ITBedrijf.PresentationModels;
using ITBedrijfProject.DataAcces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace ITBedrijf.Controllers
{
    public class VerenigingController : Controller
    {
        // GET: Vereneging
        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult Index(int? offset, int? aantal)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (!offset.HasValue) offset = 0;
            if (!aantal.HasValue) aantal = 10;
            List<Organisation> organisation = DAOrganisation.GetOrganisations(offset.Value, aantal.Value);
            List<int> numbers = LimitList.GetNumberList(LimitList.GetAantal(DAOrganisation.GetOrganisationsCount(), aantal.Value));
            ViewBag.Organisation = organisation;
            ViewBag.Numbers = numbers;
            ViewBag.Length = numbers.Count();
            return View();

        }

        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult NewOrganisation()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            return View();
        }

        [HttpPost]
        public ActionResult NewOrganisation(PMOrganisation organisation)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");

            if (ModelState.IsValid)
            {
                if (DAOrganisation.InsertOrganisation(organisation) < 0)
                {
                    organisation.Error = "Login Naam Database bestaat al.";
                    return View(organisation);
                }
                var hub = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<Counters>();
                int amountOrganisations = DAOrganisation.GetOrganisationsCount();
                hub.Clients.All.NumberOffOrganisations(amountOrganisations);
                return RedirectToAction("Index");
            }
            return View(organisation);
        }

        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult Details(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            PMOrganisation organisation = DAOrganisation.GetOrganisationById(id);
            return View(organisation);
        }

        [HttpPost]
        public ActionResult Details()
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            return RedirectToAction("Index");
        }

        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult Edit(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            PMOrganisation organisation = DAOrganisation.GetOrganisationById(id);
            return View(organisation);
        }

        [HttpPost]
        public ActionResult Edit(PMOrganisation organisation, int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (ModelState.IsValid)
            {
                DAOrganisation.UpdateOrganisation(id, organisation);
                return RedirectToAction("Index");
            }
            return View("Edit", organisation);
        }

        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult Register(int id, int? offset, int? aantal)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            if (!offset.HasValue) offset = 0;
            if (!aantal.HasValue) aantal = 10;
            List<OrganisationRegister> register = DAOrganisationRegister.GetOrganisationRegisterById(id, offset.Value, aantal.Value);
            List<int> numbers = LimitList.GetNumberList(LimitList.GetAantal(DAOrganisationRegister.GetOrganisationRegisterCount(id), aantal.Value));
            ViewBag.Register = register;
            ViewBag.Organisation = DAOrganisation.GetOrganisationById(id);
            ViewBag.Numbers = numbers;
            ViewBag.Length = numbers.Count();
            return View();
        }

        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult NewRegister(int id)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            PMOrganisationRegister organisationRegister = new PMOrganisationRegister();
            organisationRegister.NewRegister = new MultiSelectList(DARegister.GetRegisters(0, DARegister.GetRegistersCount()), "Id", "Device", "RegisterName");
            organisationRegister.OrganisationID = id;
            ViewBag.Organisation = DAOrganisation.GetOrganisationById(id);
            return View(organisationRegister);
        }

        [HttpPost]
        public ActionResult NewRegister(int organisationID, int registerID, PMOrganisationRegister organisationRegister, DateTime? FromTime, DateTime? UntilTime)
        {
            
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            organisationRegister.OrganisationID = organisationID;
            if (ModelState.IsValid)
            {
                if (organisationRegister.FromDate >= organisationRegister.UntilDate) return RedirectToAction("Register", new { id = organisationID });
                if (FromTime.HasValue) organisationRegister.FromDate = new DateTime(organisationRegister.FromDate.Year, organisationRegister.FromDate.Month, organisationRegister.FromDate.Day, FromTime.Value.Hour, FromTime.Value.Minute, 0);
                if (UntilTime.HasValue) organisationRegister.UntilDate = new DateTime(organisationRegister.UntilDate.Year, organisationRegister.UntilDate.Month, organisationRegister.UntilDate.Day, UntilTime.Value.Hour, UntilTime.Value.Minute, 0);

                DAOrganisationRegister.InsertOrganisationRegister(organisationRegister);
                return RedirectToAction("Register", new { id = organisationID });
            }
            return RedirectToAction("NewRegister", new { id = organisationID });
        }

        [HttpGet]
        [OutputCache(CacheProfile = "CacheDefault")]
        public ActionResult EditRegister(int organisationID, int registerID)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            PMOrganisationRegister organisationRegister = new PMOrganisationRegister();
            organisationRegister.NewOrganisation = new MultiSelectList(DAOrganisation.GetOrganisations(0, DAOrganisation.GetOrganisationsCount()), "Id", "Login", "OrganisationName");
            OrganisationRegister or = DAOrganisationRegister.GetOrganisationRegisterByIds(organisationID, registerID);
            organisationRegister.Device = or.Device;
            organisationRegister.FromDate = or.FromDate;
            organisationRegister.Login = or.Login;
            organisationRegister.OrganisationID = or.OrganisationID;
            organisationRegister.OrganisationName = or.OrganisationName;
            organisationRegister.RegisterID = or.RegisterID;
            organisationRegister.RegisterName = or.RegisterName;
            organisationRegister.UntilDate = or.UntilDate;

            ViewBag.Organisation = DAOrganisation.GetOrganisationById(organisationID);
            ViewBag.oldId = organisationID;
            return View(organisationRegister);
        }

        [HttpPost]
        public ActionResult EditRegister(int oldOrganisationID, int organisationID, DateTime fromDate, DateTime untilDate, int registerID)
        {
            if (User.Identity.Name == "") return RedirectToAction("ErrorLogin", "Home");
            OrganisationRegister organisationRegister = DAOrganisationRegister.GetOrganisationRegisterByIds(organisationID, registerID);
            organisationRegister.FromDate = fromDate;
            organisationRegister.OrganisationID = organisationID;
            organisationRegister.RegisterID = registerID;
            organisationRegister.UntilDate = untilDate;
            DAOrganisationRegister.UpdateOrganisationRegister(oldOrganisationID, organisationRegister);
            return RedirectToAction("Register", new { id = oldOrganisationID });
        }
    }
}

ITBedrijf/ITBedrijf/Views/Vereniging/Details.cshtml
@model PMOrganisation
<h2>Detail</h2>
@using (Html.BeginForm("Details", "Vereniging", FormMethod.Post))
{
    <table class="form">
        <tr>
            <td class="title">Persoonlijke Gegevens</td>
            <td class="title"></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Login)</td>
            <td>@Html.ValueFor(a => a.Login)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Address)</td>
            <td>@Html.ValueFor(a => a.Address)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Email)</td>
            <td>@Html.ValueFor(a => a.Email)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Phone)</td>
            <td>@Html.ValueFor(a => a.Phone)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.OrganisationName)</td>
            <td>@Html.ValueFor(a => a.OrganisationName)</td>
        </tr>
        <tr>
            <td class="title">Database Gegevens</td>
            <td class="title"></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbLogin)</td>
            <td>@Html.ValueFor(a => a.DbLogin)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbName)</td>
            <td>@Html.ValueFor(a => a.DbName)</td>
        </tr>
        <td><input type="submit" name="Back" value="Keer Terug" /></td>
    </table>
}

ITBedrijf/ITBedrijf/Views/Vereniging/Edit.cshtml
@model PMOrganisation
<h2>Vereniging Aanpassen</h2>
@using (Html.BeginForm("Edit", "Vereniging", FormMethod.Post))
{
    @Html.HiddenFor(a => a.Id)
    @Html.HiddenFor(a => a.DbLogin)
    @Html.HiddenFor(a => a.DbName)
    @Html.HiddenFor(a => a.DbPassword)
    <input type="hidden" value="@Html.DisplayFor(a => a.DbPassword)" name="DbControlePassword" />
    <table class="form">
        <tr>
            <td class="title">Persoonlijke Gegevens</td>
            <td class="title"></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Login)</td>
            <td>@Html.TextBoxFor(a => a.Login, new { placeholder = Html.DisplayNameFor(a => a.Login) })</td>
            @Html.ValidationMessageFor(a => a.Login)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Password)</td>
            <td>@Html.PasswordFor(a => a.Password, new { placeholder = Html.DisplayNameFor(a => a.Password) })</td>
            @Html.ValidationMessageFor(a => a.Password)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.ControlePassword)</td>
            <td>@Html.PasswordFor(a => a.ControlePassword, new { placeholder = Html.DisplayNameFor(a => a.ControlePassword) })</td>
            @Html.ValidationMessageFor(a => a.ControlePassword)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Address)</td>
            <td>@Html.TextBoxFor(a => a.Address, new { placeholder = Html.DisplayNameFor(a => a.Address) })</td>
            @Html.ValidationMessageFor(a => a.Address)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Email)</td>
            <td>@Html.TextBoxFor(a => a.Email, new { placeholder = Html.DisplayNameFor(a => a.Email) })</td>
            @Html.ValidationMessageFor(a => a.Email)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Phone)</td>
            <td>@Html.TextBoxFor(a => a.Phone, new { placeholder = Html.DisplayNameFor(a => a.Phone) })</td>
            @Html.ValidationMessageFor(a => a.Phone)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.OrganisationName)</td>
            <td>@Html.TextBoxFor(a => a.OrganisationName, new { placeholder = Html.DisplayNameFor(a => a.OrganisationName) })</td>
            @Html.ValidationMessageFor(a => a.OrganisationName)
        </tr>
        <tr>
            <td><input type="submit" name="Update" value="Aanpassen" /></td>
            <td>
                <a href="/Vereniging/Index">
                    <input type="button" value="Keer Terug" />
                </a>
            </td>
        </tr>
    </table>
}

ITBedrijf/ITBedrijf/Views/Vereniging/EditRegister.cshtml
@model PMOrganisationRegister
<h2>Kassa Aanpassen @ViewBag.Organisation.OrganisationName:@ViewBag.Organisation.Login</h2>
@using (Html.BeginForm("EditRegister", "Vereniging", FormMethod.Post))
{
    <input type="hidden" name="oldOrganisationID" id="oldOrganisationID" value="@ViewBag.oldId" />
    @Html.HiddenFor(a => a.RegisterID)
    @Html.HiddenFor(a => a.FromDate)
    @Html.HiddenFor(a => a.UntilDate)
    <table class="form">
        <tr>
            <td>@Html.LabelFor(a => a.OrganisationName)</td>
            <td>@Html.DropDownListFor(a => a.OrganisationID, Model.NewOrganisation)</td>
            @Html.ValidationMessageFor(a => a.OrganisationID)
        </tr>
        <tr>
            <td><input type="submit" value="Aanpassen" /></td>
            <td>
                <a href="/Vereniging/Register?id=@ViewBag.oldId">
                    <input type="button" value="Keer Terug" />
                </a>
            </td>
        </tr>
    </table>
}

ITBedrijf/ITBedrijf/Views/Vereniging/Index.cshtml
@model PMOrganisation
<script src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
<script src="~/signalr/hubs"></script>
<h2>Vereniging Overzicht</h2>
<p id="amountOrganisations"></p>
<table>
    <tr class="header">
        <td>@Html.LabelFor(a => a.OrganisationName)</td>
        <td>@Html.LabelFor(a => a.Address)</td>
        <td>@Html.LabelFor(a => a.Email)</td>
        <td>@Html.LabelFor(a => a.Phone)</td>
        <td></td>
    </tr>
    @foreach (var item in @ViewBag.Organisation)
    {
        <tr class="item">
            <td>@item.OrganisationName</td>
            <td>@item.Address</td>
            <td>@item.Email</td>
            <td>@item.Phone</td>
            <td><a href="/Vereniging/Details?id=@item.Id">Details</a> | <a href="/Vereniging/Register?id=@item.Id">Kassa's | <a href="/Vereniging/Edit?id=@item.Id">Bewerken</a>
        </tr>
    }
    <tr class="link">
        <td><a href="/Vereniging/NewOrganisation">Vereniging Toevoegen</a></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
<p>
    @foreach (var item in @ViewBag.Numbers)
    {
        if (@item != @ViewBag.Length - 1)
        {
            <a href="/Vereniging/Index?Offset=@item">@item</a>
            <span> - </span>
        }
        else
        {
            <a href="/Vereniging/Index?Offset=@item">@item</a>
        }
    }
</p>
<script>
    $(function () {
        var counters = $.connection.counters;
        $.connection.hub.start().done(function () {
            counters.server.getAmountOrganisations();
        });

        counters.client.numberOffOrganisations = function (numberOffFiles) {
            $('#amountOrganisations').text("Totaal aantal Verenigingen: " + numberOffFiles);
        }
    });
</script>

ITBedrijf/ITBedrijf/Views/Vereniging/NewOrganisation.cshtml
@model PMOrganisation
<h2>Vereniging Toevoegen</h2>
@using (Html.BeginForm("NewOrganisation", "Vereniging", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <p class="field-validation-error">@Html.DisplayFor(a => a.Error)</p>
    <table class="form">
        <tr>
            <td class="title">Persoonlijke Gegevens</td>
            <td class="title"></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Login)</td>
            <td>@Html.TextBoxFor(a => a.Login, new { placeholder = Html.DisplayNameFor(a => a.Login) })</td>
            @Html.ValidationMessageFor(a => a.Login)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Password)</td>
            <td>@Html.PasswordFor(a => a.Password, new { placeholder = Html.DisplayNameFor(a => a.Password) })</td>
            @Html.ValidationMessageFor(a => a.Password)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.ControlePassword)</td>
            <td>@Html.PasswordFor(a => a.ControlePassword, new { placeholder = Html.DisplayNameFor(a => a.ControlePassword) })</td>
            @Html.ValidationMessageFor(a => a.ControlePassword)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Address)</td>
            <td>@Html.TextBoxFor(a => a.Address, new { placeholder = Html.DisplayNameFor(a => a.Address) })</td>
            @Html.ValidationMessageFor(a => a.Address)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Email)</td>
            <td>@Html.TextBoxFor(a => a.Email, new { placeholder = Html.DisplayNameFor(a => a.Email) })</td>
            @Html.ValidationMessageFor(a => a.Email)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Phone)</td>
            <td>@Html.TextBoxFor(a => a.Phone, new { placeholder = Html.DisplayNameFor(a => a.Phone) })</td>
            @Html.ValidationMessageFor(a => a.Phone)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.OrganisationName)</td>
            <td>@Html.TextBoxFor(a => a.OrganisationName, new { placeholder = Html.DisplayNameFor(a => a.OrganisationName) })</td>
            @Html.ValidationMessageFor(a => a.OrganisationName)
        </tr>
        <tr>
            <td class="title">Database Gegevens</td>
            <td class="title"></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbLogin)</td>
            <td>@Html.TextBoxFor(a => a.DbLogin, new { placeholder = Html.DisplayNameFor(a => a.DbLogin) })</td>
            @Html.ValidationMessageFor(a => a.DbLogin)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbName)</td>
            <td>@Html.TextBoxFor(a => a.DbName, new { placeholder = Html.DisplayNameFor(a => a.DbName) })</td>
            @Html.ValidationMessageFor(a => a.DbName)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbPassword)</td>
            <td>@Html.PasswordFor(a => a.DbPassword, new { placeholder = Html.DisplayNameFor(a => a.DbPassword) })</td>
            @Html.ValidationMessageFor(a => a.DbPassword)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.DbControlePassword)</td>
            <td>@Html.PasswordFor(a => a.DbControlePassword, new { placeholder = Html.DisplayNameFor(a => a.DbControlePassword) })</td>
            @Html.ValidationMessageFor(a => a.DbControlePassword)
        </tr>
        <tr>
            <td><input class="inputWidth" type="submit" value="Vereniging Toevoegen" /></td>
            <td>
                <a href="/Vereniging/Index">
                    <input class="inputWidth" type="button" value="Keer Terug" />
                </a>
            </td>
        </tr>
    </table>
}

ITBedrijf/ITBedrijf/Views/Vereniging/NewRegister.cshtml
@model PMOrganisationRegister
<h2>Kassa Toevoegen aan @ViewBag.Organisation.OrganisationName:@ViewBag.Organisation.Login</h2>
@using (Html.BeginForm("NewRegister", "Vereniging", FormMethod.Post))
{
    @Html.HiddenFor(a => a.OrganisationID)
    <table class="form">
        <tr>
            <td>@Html.LabelFor(a => a.RegisterID)</td>
            <td>@Html.DropDownListFor(a => a.RegisterID, Model.NewRegister)</td>
            @Html.ValidationMessageFor(a => a.RegisterID)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.FromDate)</td>
            <td><input type="date" value="@DateTime.Today" id="FromDate" name="FromDate" min="@DateTime.Today.Year-@DateTime.Today.Month-@DateTime.Today.Day" /></td>
            <td><input type="time" value="@DateTime.Today" id="FromTime" name="FromTime" /></td>
            @Html.ValidationMessageFor(a => a.FromDate)
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.UntilDate)</td>
            <td><input type="date" value="@DateTime.Today" id="UntilDate" name="UntilDate" min="@DateTime.Today.Year-@DateTime.Today.Month-@DateTime.Today.Day" /></td>
            <td><input type="time" value="@DateTime.Today" id="UntilTime" name="UntilTime" /></td>
            @Html.ValidationMessageFor(a => a.UntilDate)
        </tr>
        <tr>
            <td><input type="submit" value="Toevoegen" /></td>
            <td>
                <a href="/Vereniging/Register?id=@Html.DisplayFor(a => a.OrganisationID)">
                    <input type="button" value="Keer Terug" />
                </a>
            </td>
        </tr>
    </table>
}

ITBedrijf/ITBedrijf/Views/Vereniging/Register.cshtml
@model PMOrganisationRegister
<h2>Kassa's voor @ViewBag.Organisation.OrganisationName:@ViewBag.Organisation.Login</h2>
<table>
    <tr class="header">
        <td class="longer">@Html.LabelFor(a => a.OrganisationName):@Html.LabelFor(a => a.Login)</td>
        <td class="longer">@Html.LabelFor(a => a.RegisterName):@Html.LabelFor(a => a.Device)</td>
        <td>@Html.LabelFor(a => a.FromDate)</td>
        <td>@Html.LabelFor(a => a.UntilDate)</td>
        <td></td>
    </tr>
    @foreach (var item in @ViewBag.Register)
    {
        <tr class="item">
            <td class="longer">@item.OrganisationName:@item.Login</td>
            <td class="longer">@item.RegisterName:@item.Device</td>
            <td>@item.FromDate</td>
            <td>@item.UntilDate</td>
            <td><a href="/Vereniging/EditRegister?organisationID=@ViewBag.Organisation.Id&registerID=@item.RegisterID">Bewerken</a></td>
        </tr>
    }
    <tr class="link">
        <td class="longer"><a href="/Vereniging/NewRegister?id=@ViewBag.Organisation.Id">Kassa Toevoegen</a></td>
        <td class="longer"><a href="/Vereniging/Index">Keer Terug</a></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
<p>
    @foreach (var item in @ViewBag.Numbers)
    {
        if (@item != @ViewBag.Length - 1)
        {
            <a href="/Vereniging/Register?id=@ViewBag.Organisation.Id&Offset=@item">@item</a>
            <span> - </span>
        }
        else
        {
            <a href="/Vereniging/Register?id=@ViewBag.Organisation.Id&Offset=@item">@item</a>
        }
    }
</p>